Feature/module02
Karpov-D/java-reboot pull request #3
Opened 2023-10-25 03:26 UTC by Karpov-D

2023-10-28 18:12 UTC, rsmitt commented on module02/src/main/java/ru/sberbank/edu/SaveFile.java
> +            writerResult.close();
если произойдет где то сверху ошибка ресурс не закроется. Используйте try with resources

2023-10-28 18:13 UTC, rsmitt commented on module02/src/main/java/ru/sberbank/edu/StatisticFile.java
> +        fileReader.close();
если произойдет где то сверху ошибка ресурс не закроется. Используйте try with resources

2023-10-28 18:13 UTC, rsmitt commented on module02/src/main/java/ru/sberbank/edu/StatisticFile.java
> +        fileReader.close();
если произойдет где то сверху ошибка ресурс не закроется. Используйте try with resources

2023-10-28 18:14 UTC, rsmitt requested changes
код нормальный, только ресурс не корректно закрываете. Поправьте пожалуйста

2023-10-30 02:46 UTC, Karpov-D commented on module02/src/main/java/ru/sberbank/edu/SaveFile.java
> +            writerResult.close();
Исправлено в комите: [Закрытие файла изменено на try with resources]

2023-10-30 02:46 UTC, Karpov-D commented on module02/src/main/java/ru/sberbank/edu/StatisticFile.java
> +        fileReader.close();
Исправлено в комите: [Закрытие файла изменено на try with resources]

2023-10-30 02:47 UTC, Karpov-D commented on module02/src/main/java/ru/sberbank/edu/StatisticFile.java
> +        fileReader.close();
Исправлено в комите: [Закрытие файла изменено на try with resources]

2023-11-05 05:45 UTC, rsmitt commented on module02/src/main/java/ru/sberbank/edu/StatisticFile.java
> +        save.save(lineCount, spaceCount, line);
save.save читается не очень хорошо, лучше избегать такое

2023-11-05 05:45 UTC, rsmitt approved these changes

2023-11-07 03:10 UTC, merged